<?php

namespace AppBundle\Repository;

/**
 * DiningTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiningTableRepository extends \Doctrine\ORM\EntityRepository
{
}
